### ISSUE TITLE
Gatsby example?

### ISSUE THREAD

**Issue by JackZheng10** [rcaferati/ras-fullpage-strategies#2]
Hey, was wondering if there's an example for Gatbsy like the main README said there was.

Tried to implement it, but only got it partially working (very buggy). I'm sure there's something I'm missing :). Thanks!

**Comment by psyopus69** [comment]
Hi!
I try build fullpage strategies on gatsby, and it works crookedly.
You did it?

My gatsby demo repo:
https://github.com/psyopus69/gatsbySimpleAwesomeSlider

On next.js all works correctly.
